- name: installing the Database on the Controller
  yum: 
    name: "{{ item }}"
    state: installed
  with_items:
    - mariadb 
    - mariadb-server 
    - python2-PyMySQL
    - MySQL-python

- name: Configuring the Database service
  template:
    src: openstack.cnf
    dest: /etc/my.cnf.d/openstack.cnf

- name: Starting the Database service
  service:
    name: mariadb
    state: started
    enabled: true

- name: Add .my.cnf
  template: src=my_cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Setting the mariadb root password
  mysql_user: 
    login_password: "{{ mysql_password }}" 
    check_implicit_admin: yes 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_password }}" 
    state: present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False


