- name: Installing the Memcached Packages
  yum: 
    name: "{{ item }}"
    state: installed
  with_items:
    - memcached 
    - python-memcached

- name: Configuring the Memcached 
  template:
    src: memcached
    dest: /etc/sysconfig/memcached

- name: Starting the Memcached Service
  service:
    name: memcached
    state: started
    enabled: true
