- name: Reboot server
  shell: sleep 1 && shutdown -r now  "Ansible trigged shutdown"
  poll: 0
  async: 1

- name: Reboot server
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started

